name: flexconsumptionplan
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
description: Azure Functions Flex Consumption Demo
config:
  pulumi:tags:
    value:
      pulumi:template: azure-typescript
